/**
 * sync-version.mjs
 *
 * Reads the package name and version from the nearest `package.json` and writes
 * a `version.ts` file into the source directory. This is used by each SDK
 * package to stamp a `data-viostream-sdk` attribute on the player container,
 * identifying the package and version at runtime.
 *
 * Usage (from any package directory):
 *   node ../../scripts/sync-version.mjs
 *
 * By default the output is written to `src/version.ts`. For packages with a
 * different source layout (e.g. Svelte's `src/lib/`), pass the output path:
 *   node ../../scripts/sync-version.mjs src/lib/version.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const pkgPath = resolve(process.cwd(), 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));

// Strip the npm scope (e.g. "@viostream/viostream-player-core" → "viostream-player-core")
const name = pkg.name.replace(/^@[^/]+\//, '');
const version = pkg.version;

// Output path: first CLI arg, or default to src/version.ts
const outPath = resolve(process.cwd(), process.argv[2] ?? 'src/version.ts');

const content = `// Auto-generated by scripts/sync-version.mjs — do not edit
export const SDK_NAME = '${name}';
export const SDK_VERSION = '${version}';
`;

writeFileSync(outPath, content, 'utf-8');
