on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build player-core
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build
        working-directory: packages/viostream-player-core

      - name: Publish player-core
        if: ${{ steps.release.outputs['packages/viostream-player-core--release_created'] }}
        run: npm publish
        working-directory: packages/viostream-player-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build player-svelte
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build
        working-directory: packages/viostream-player-svelte

      - name: Publish player-svelte
        if: ${{ steps.release.outputs['packages/viostream-player-svelte--release_created'] }}
        run: npm publish
        working-directory: packages/viostream-player-svelte
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build player-react
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build
        working-directory: packages/viostream-player-react

      - name: Publish player-react
        if: ${{ steps.release.outputs['packages/viostream-player-react--release_created'] }}
        run: npm publish
        working-directory: packages/viostream-player-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
